### ISSUE TITLE
Is it possible to go back to default plot theme by Wolframe?

### ISSUE THREAD

**Issue by quarkquartet** [EverettYou/Mathematica-for-physics#1]
After install the packages, I found that the definition of named colors seems to be changed. For example, the color "Blue, Opacity[0.2]" produces different color as I did before I installed the packages. In addition, it seems that "BaseStyle -> {FontSize, FontFamily}" command cannot change the frame label anymore. Are there anyway to go back to the default color and define the frame style freely?

**Comment by EverettYou** [comment]
* To restore the original Mathematica definition of named colors:
1. open [Kernel/init.m](https://github.com/EverettYou/Mathematica-for-physics/blob/master/Kernel/init.m) on your local machine
2. comment out line 10, like ``(* Needs["Themes`"]; *)``
3. run the [install.m](https://github.com/EverettYou/Mathematica-for-physics/blob/master/install.m) again and restart Mathematica.

*Explanation*: Colors (`Red`, `Blue` etc.) are redefined in the `Themes` package to be less saturated (see line 12 of [Themes/Academic.m](https://github.com/EverettYou/Mathematica-for-physics/blob/master/Themes/Academic.m)). By removing the ``Needs["Themes`"];`` statement from the kernel initialization file, Mathematica will not autoload the package and hence will remain its original definition of colors. If you want to use the `Themes` package, you can load it by ``<< Themes` `` manually.

* To enable the `BaseStyle` option for frame tick style setting, simply stop using the `CMU Article` style sheet (use any other style sheet provided by Mathematica). If you don't want `CMU Article` to be loaded as the default style sheet:
1. open [FrontEnd/init.m](https://github.com/EverettYou/Mathematica-for-physics/blob/master/FrontEnd/init.m) on your local machine
2. comment out line 7, like `(* DefaultStyleDefinitions->"CMU Article.nb", *)`
3. run the [install.m](https://github.com/EverettYou/Mathematica-for-physics/blob/master/install.m) again and restart Mathematica. 

*Explanation*: The `CMU Article` style sheet rewrites the `BaseStyle` option on the Notebook level, in order to set the font family and size to the designed style. It also modifies the `DefaultFrameTicksStyle` option to set the frame tick style. So the frame tick style can no longer be set by the `BaseStyle` option (because `DefaultFrameTicksStyle` overrides it). But the idea is that you can always set the frame tick style explicitly by the `FrameTickStyle` option in your code.

**Comment by quarkquartet** [comment]
> 

Hi, Everett,

Thank you for your reply after such a long time. I have figured out them and understood the structure of Mathematica configuration file. Your reply is in very detail and confirmed my understanding. I even wrote my private configuration (forked from you as a template). Please take my sincere appreciation.
