### ISSUE TITLE
Quit Kernel Bug in the CMU Article Stylesheet

### ISSUE THREAD

**Issue by subhodeeps** [EverettYou/Mathematica-for-physics#2]
Hi,

I noticed something strange: usually, when one quits the Mathematica kernel, the input and output cell numbers are reset. It becomes grayed out and no number is displayed. 

But when I apply the stylesheet to a notebook, I notice that after quitting the kernel (either from the menu or docked cell), the input/output cell numbers are not reset and it remains blue.

Is this a feature or a bug? Is there a way to go back to the original behavior?

**Comment by EverettYou** [comment]
Thanks for pointing out this issue. After some research, I believe that this is a new behavior of Mathematica starting from 11.3 (released on 03/08/2018) right after the CMU Article stylesheet was originally made (02/18/2018). I did not notice this change until now because I have been using the CMU Article stylesheet since then. I have now updated the stylesheet [CMU Article.nb](https://github.com/EverettYou/Mathematica-for-physics/blob/master/FrontEnd/CMU%20Article.nb) to incorporate this behavior. Please reinstall the new stylesheet.
